### Functions for computing the output of the Perceptron ###

In [1]:
import numpy as np

In [2]:
# Summation function
# This function takes W,b and X as inputs
# W and X are matrices and should have the shape nx1 and mxn
# b is a matrix of shape mx1

def summation(W,X,b):
    sigma = np.dot(X,W) + b
    return sigma
    

In [3]:
# Sigmoid function
# It takes as input the summation result

def sigmoid(z):
    return 1/(1 + np.exp(-z))

In [4]:
# Initialize inputs values.

X = np.array([[2,1]])
W = np.array([[0.5],[0.5]])
b = np.array([0.5])

print(f"Shapes of X, W and b:{X.shape, W.shape,b.shape}")

Shapes of X, W and b:((1, 2), (2, 1), (1,))


In [5]:
# Test the functions function

output = sigmoid(summation(W,X,b))
print(output)

[[0.88079708]]


In [6]:
# New data

X1 = np.array([1,5,2,6,3,7,4,8,1,0]).reshape(5,2)
print(f"Shape of X: {X1.shape} and X:\n{X1}")

Shape of X: (5, 2) and X:
[[1 5]
 [2 6]
 [3 7]
 [4 8]
 [1 0]]


In [7]:
# Test function with new data

output = sigmoid(summation(W,X1,b))
print(output)

[[0.97068777]
 [0.98901306]
 [0.99592986]
 [0.99849882]
 [0.73105858]]


In [8]:
# lets do a manual calculation on the first row of data to check our results

zz = b + 1*0.5 + 5*0.5
print(f"Output = {1/(1 + np.exp(-zz))}")

Output = [0.97068777]


## Extra ##

### How to convert the whole thing into a class to enable these computations by creating objects ###

In [9]:
class Neuron:
    def __init__(self,W,X,b):
        self.W = W
        self.X = X
        self.b = b
        
    def summation(self):
        return np.dot(self.X,self.W) + self.b
    
    def sigmoid(self):
        return 1/(1 + np.exp(-self.summation()))

In [10]:
# Instantiate  objects

neuron1 = Neuron(W,X,b)
neuron2 = Neuron(W,X1,b)


In [11]:
# neuron 1 output

print(f"Summation: {neuron1.summation()}")
print(f"Activation Output: {neuron1.sigmoid()}")

Summation: [[2.]]
Activation Output: [[0.88079708]]


In [12]:
# neuron 2 output

print(f"Summation:\n{neuron2.summation()}")
print(f"Activation Output:\n{neuron2.sigmoid()}")

Summation:
[[3.5]
 [4.5]
 [5.5]
 [6.5]
 [1. ]]
Activation Output:
[[0.97068777]
 [0.98901306]
 [0.99592986]
 [0.99849882]
 [0.73105858]]


In [13]:
# We could also do

print(neuron1.sigmoid(),'\n')
print(neuron2.sigmoid())

[[0.88079708]] 

[[0.97068777]
 [0.98901306]
 [0.99592986]
 [0.99849882]
 [0.73105858]]
